import localFont from "next/font/local";

import { Suspense } from "react";
import Nav from "../../src/components/organisms/Header";
import Footer from "../../src/components/Footer";
import '../styles/global.scss'
import LoadingScreen from "../components/templates/LoadingScreen";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <meta charSet="utf-8" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"></meta>
      <head> 
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
      </head>



      <body

      >
        <Suspense fallback={<LoadingScreen/>}>
          <Nav />

          {children}
          <Footer />
        </Suspense>
        <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
      </body>
    </html>
  );
}
